<?xml version="1.0" encoding="UTF-8"?><testsuite name="Chrome_390217171_Mac_OS.secretaryDB" errors="7" failures="0" tests="7" time="0.006">
<testcase classname="Chrome_390217171_Mac_OS.secretaryDB" name="test test for secretary initialisation for the first time" time="0.001">
<error type="error">[{"message":"assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/secretaryDB_test.js:17:38)\n    at QUnitTestCase.(anonymous function) [as test test for secretary initialisation for the first time] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at InstrumentedTestCaseRunnerPlugin.runTestConfiguration (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:221:20)","name":"Error","stack":"Error: assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/secretaryDB_test.js:17:38)\n    at QUnitTestCase.(anonymous function) [as test test for secretary initialisation for the first time] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at InstrumentedTestCaseRunnerPlugin.runTestConfiguration (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:221:20)\n    at F.extend.push (http://code.jquery.com/qunit/qunit-1.12.0.js:917:10)\n    at assert.deepEqual (http://code.jquery.com/qunit/qunit-1.12.0.js:593:9)\n    at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/secretaryDB_test.js:17:38)\n    at QUnitTestCase.(anonymous function) [as test test for secretary initialisation for the first time] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at InstrumentedTestCaseRunnerPlugin.runTestConfiguration (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:221:20)\n    at jstestdriver.PluginRegistrar.dispatch_ (http://localhost:9876/static/runner.js:1603:26)"}]</error>
</testcase>
<testcase classname="Chrome_390217171_Mac_OS.secretaryDB" name="test test for secretary initialisation with reloading local storage's content" time="0.001">
<error type="error">[{"message":"assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/secretaryDB_test.js:43:51)\n    at QUnitTestCase.(anonymous function) [as test test for secretary initialisation with reloading local storage's content] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)","name":"Error","stack":"Error: assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/secretaryDB_test.js:43:51)\n    at QUnitTestCase.(anonymous function) [as test test for secretary initialisation with reloading local storage's content] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)\n    at F.extend.push (http://code.jquery.com/qunit/qunit-1.12.0.js:917:10)\n    at assert.equal (http://code.jquery.com/qunit/qunit-1.12.0.js:556:9)\n    at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/secretaryDB_test.js:43:51)\n    at QUnitTestCase.(anonymous function) [as test test for secretary initialisation with reloading local storage's content] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)"}]</error>
</testcase>
<testcase classname="Chrome_390217171_Mac_OS.secretaryDB" name="test test for adding a secretary" time="0.001">
<error type="error">[{"message":"assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/secretaryDB_test.js:55:48)\n    at QUnitTestCase.(anonymous function) [as test test for adding a secretary] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)","name":"Error","stack":"Error: assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/secretaryDB_test.js:55:48)\n    at QUnitTestCase.(anonymous function) [as test test for adding a secretary] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)\n    at F.extend.push (http://code.jquery.com/qunit/qunit-1.12.0.js:917:10)\n    at assert.equal (http://code.jquery.com/qunit/qunit-1.12.0.js:556:9)\n    at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/secretaryDB_test.js:55:48)\n    at QUnitTestCase.(anonymous function) [as test test for adding a secretary] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)"}]</error>
</testcase>
<testcase classname="Chrome_390217171_Mac_OS.secretaryDB" name="test test for adding a secretary object" time="0.0">
<error type="error">[{"message":"assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/secretaryDB_test.js:70:48)\n    at QUnitTestCase.(anonymous function) [as test test for adding a secretary object] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)","name":"Error","stack":"Error: assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/secretaryDB_test.js:70:48)\n    at QUnitTestCase.(anonymous function) [as test test for adding a secretary object] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)\n    at F.extend.push (http://code.jquery.com/qunit/qunit-1.12.0.js:917:10)\n    at assert.equal (http://code.jquery.com/qunit/qunit-1.12.0.js:556:9)\n    at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/secretaryDB_test.js:70:48)\n    at QUnitTestCase.(anonymous function) [as test test for adding a secretary object] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)"}]</error>
</testcase>
<testcase classname="Chrome_390217171_Mac_OS.secretaryDB" name="test test login" time="0.002">
<error type="error">[{"message":"assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/secretaryDB_test.js:87:48)\n    at QUnitTestCase.(anonymous function) [as test test login] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)","name":"Error","stack":"Error: assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/secretaryDB_test.js:87:48)\n    at QUnitTestCase.(anonymous function) [as test test login] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)\n    at F.extend.push (http://code.jquery.com/qunit/qunit-1.12.0.js:917:10)\n    at assert.equal (http://code.jquery.com/qunit/qunit-1.12.0.js:556:9)\n    at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/secretaryDB_test.js:87:48)\n    at QUnitTestCase.(anonymous function) [as test test login] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)"}]</error>
</testcase>
<testcase classname="Chrome_390217171_Mac_OS.secretaryDB" name="test test a secretary's existence" time="0.0">
<error type="error">[{"message":"assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/secretaryDB_test.js:103:49)\n    at QUnitTestCase.(anonymous function) [as test test a secretary's existence] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)","name":"Error","stack":"Error: assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/secretaryDB_test.js:103:49)\n    at QUnitTestCase.(anonymous function) [as test test a secretary's existence] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)\n    at F.extend.push (http://code.jquery.com/qunit/qunit-1.12.0.js:917:10)\n    at assert.equal (http://code.jquery.com/qunit/qunit-1.12.0.js:556:9)\n    at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/secretaryDB_test.js:103:49)\n    at QUnitTestCase.(anonymous function) [as test test a secretary's existence] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)"}]</error>
</testcase>
<testcase classname="Chrome_390217171_Mac_OS.secretaryDB" name="test test secretary close operation" time="0.001">
<error type="error">[{"message":"assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/secretaryDB_test.js:126:49)\n    at QUnitTestCase.(anonymous function) [as test test secretary close operation] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)","name":"Error","stack":"Error: assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/secretaryDB_test.js:126:49)\n    at QUnitTestCase.(anonymous function) [as test test secretary close operation] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)\n    at F.extend.push (http://code.jquery.com/qunit/qunit-1.12.0.js:917:10)\n    at assert.equal (http://code.jquery.com/qunit/qunit-1.12.0.js:556:9)\n    at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/secretaryDB_test.js:126:49)\n    at QUnitTestCase.(anonymous function) [as test test secretary close operation] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)"}]</error>
</testcase>
</testsuite>
