<?xml version="1.0" encoding="UTF-8"?><testsuite name="Chrome_390217171_Mac_OS.classDB" errors="5" failures="0" tests="6" time="0.011000001">
<testcase classname="Chrome_390217171_Mac_OS.classDB" name="test test for class initialisation for the first time" time="0.003">
<error type="error">[{"message":"assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/classDB_test.js:15:37)\n    at QUnitTestCase.(anonymous function) [as test test for class initialisation for the first time] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at InstrumentedTestCaseRunnerPlugin.runTestConfiguration (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:221:20)","name":"Error","stack":"Error: assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/classDB_test.js:15:37)\n    at QUnitTestCase.(anonymous function) [as test test for class initialisation for the first time] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at InstrumentedTestCaseRunnerPlugin.runTestConfiguration (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:221:20)\n    at F.extend.push (http://code.jquery.com/qunit/qunit-1.12.0.js:917:10)\n    at assert.deepEqual (http://code.jquery.com/qunit/qunit-1.12.0.js:593:9)\n    at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/classDB_test.js:15:37)\n    at QUnitTestCase.(anonymous function) [as test test for class initialisation for the first time] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at InstrumentedTestCaseRunnerPlugin.runTestConfiguration (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:221:20)\n    at jstestdriver.PluginRegistrar.dispatch_ (http://localhost:9876/static/runner.js:1603:26)"}]</error>
</testcase>
<testcase classname="Chrome_390217171_Mac_OS.classDB" name="test test for class initialisation with reloading local storage's content" time="0.003">
<error type="error">[{"message":"assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/classDB_test.js:47:46)\n    at QUnitTestCase.(anonymous function) [as test test for class initialisation with reloading local storage's content] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)","name":"Error","stack":"Error: assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/classDB_test.js:47:46)\n    at QUnitTestCase.(anonymous function) [as test test for class initialisation with reloading local storage's content] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)\n    at F.extend.push (http://code.jquery.com/qunit/qunit-1.12.0.js:917:10)\n    at assert.equal (http://code.jquery.com/qunit/qunit-1.12.0.js:556:9)\n    at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/classDB_test.js:47:46)\n    at QUnitTestCase.(anonymous function) [as test test for class initialisation with reloading local storage's content] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)"}]</error>
</testcase>
<testcase classname="Chrome_390217171_Mac_OS.classDB" name="test test for adding a drive class" time="0.0"/>
<testcase classname="Chrome_390217171_Mac_OS.classDB" name="test test for getting a class by its id" time="0.001">
<error type="error">[{"message":"assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/classDB_test.js:103:34)\n    at QUnitTestCase.(anonymous function) [as test test for getting a class by its id] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)","name":"Error","stack":"Error: assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/classDB_test.js:103:34)\n    at QUnitTestCase.(anonymous function) [as test test for getting a class by its id] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)\n    at F.extend.push (http://code.jquery.com/qunit/qunit-1.12.0.js:917:10)\n    at assert.equal (http://code.jquery.com/qunit/qunit-1.12.0.js:556:9)\n    at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/classDB_test.js:103:34)\n    at QUnitTestCase.(anonymous function) [as test test for getting a class by its id] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)"}]</error>
</testcase>
<testcase classname="Chrome_390217171_Mac_OS.classDB" name="test test for checking a class's existence" time="0.002">
<error type="error">[{"message":"assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/classDB_test.js:123:25)\n    at QUnitTestCase.(anonymous function) [as test test for checking a class's existence] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)","name":"Error","stack":"Error: assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/classDB_test.js:123:25)\n    at QUnitTestCase.(anonymous function) [as test test for checking a class's existence] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)\n    at F.extend.push (http://code.jquery.com/qunit/qunit-1.12.0.js:917:10)\n    at assert.equal (http://code.jquery.com/qunit/qunit-1.12.0.js:556:9)\n    at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/classDB_test.js:123:25)\n    at QUnitTestCase.(anonymous function) [as test test for checking a class's existence] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)"}]</error>
</testcase>
<testcase classname="Chrome_390217171_Mac_OS.classDB" name="test test for deleting a class from class database" time="0.002">
<error type="error">[{"message":"assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/classDB_test.js:146:25)\n    at QUnitTestCase.(anonymous function) [as test test for deleting a class from class database] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)","name":"Error","stack":"Error: assertion outside test context, was     at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/classDB_test.js:146:25)\n    at QUnitTestCase.(anonymous function) [as test test for deleting a class from class database] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)\n    at F.extend.push (http://code.jquery.com/qunit/qunit-1.12.0.js:917:10)\n    at assert.equal (http://code.jquery.com/qunit/qunit-1.12.0.js:556:9)\n    at Object.&lt;anonymous&gt; (http://localhost:9876/test/test/qunit/model/database/classDB_test.js:146:25)\n    at QUnitTestCase.(anonymous function) [as test test for deleting a class from class database] (http://localhost:9876/test/test/qunit/QUnitAdapter.js:47:37)\n    at jstestdriver.plugins.TestRunnerPlugin.runTest (http://localhost:9876/static/runner.js:5403:33)\n    at TestResultIterator.runTest (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:201:28)\n    at TestResultIterator.runNext (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:292:10)\n    at InstrumentedTestCaseRunner.run (http://localhost:9876/test/com/google/jstestdriver/coverage/javascript/LCOV.js:250:27)\n    at bound (http://localhost:9876/static/jstestdrivernamespace.js:71:17)"}]</error>
</testcase>
</testsuite>
